In [3]:
import pandas as pd
import requests

In [15]:
res=requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [17]:
res.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/avedvodAZUcwqevBfm8p4G2NziQ.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 182.493,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.705,
   'vote_count': 26549},
  {'adult': False,
   'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 318.866,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.691,
   'vote_count': 20154},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 131.333,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather Part II',
   'video': False,
   'vote_average': 8.575,
   'vote_count': 12161},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 128.348,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.565,
   'vote_count': 15565},
  {'adult': False,
   'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 99.355,
   'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.543,
   'vote_count': 8413},
  {'adult': False,
   'backdrop_path': '/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 148.324,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-04-18',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.537,
   'vote_count': 16172},
  {'adult': False,
   'backdrop_path': '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 88.589,
   'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg',
   'release_date': '1995-10-20',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.536,
   'vote_count': 4410},
  {'adult': False,
   'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
   'genre_ids': [18, 28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 202.793,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.516,
   'vote_count': 32300},
  {'adult': False,
   'backdrop_path': '/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 114.818,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.508,
   'vote_count': 17831},
  {'adult': False,
   'backdrop_path': '/vxJ08SvwomfKbpboCWynC3uqUg4.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 121.062,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.506,
   'vote_count': 17053},
  {'adult': False,
   'backdrop_path': '/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 142.0,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.488,
   'vote_count': 11147},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 139.372,
   'poster_path': '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 27443},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 194.104,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-01',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.482,
   'vote_count': 23698},
  {'adult': False,
   'backdrop_path': '/ghgfzbEV7kbpbi1O8eIILKVXEA8.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 13,
   'original_language': 'en',
   'original_title': 'Forrest Gump',
   'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
   'popularity': 141.203,
   'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
   'release_date': '1994-06-23',
   'title': 'Forrest Gump',
   'video': False,
   'vote_average': 8.475,
   'vote_count': 26946},
  {'adult': False,
   'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 123.889,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-22',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.465,
   'vote_count': 8401},
  {'adult': False,
   'backdrop_path': '/d6UxFCGQxpszcf8mwgGjQ3ynqGl.jpg',
   'genre_ids': [18, 80],
   'id': 769,
   'original_language': 'en',
   'original_title': 'GoodFellas',
   'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
   'popularity': 112.482,
   'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
   'release_date': '1990-09-12',
   'title': 'GoodFellas',
   'video': False,
   'vote_average': 8.464,
   'vote_count': 12591},
  {'adult': False,
   'backdrop_path': '/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg',
   'genre_ids': [28, 18],
   'id': 346,
   'original_language': 'ja',
   'original_title': '七人の侍',
   'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
   'popularity': 86.673,
   'poster_path': '/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg',
   'release_date': '1954-04-26',
   'title': 'Seven Samurai',
   'video': False,
   'vote_average': 8.461,
   'vote_count': 3571},
  {'adult': False,
   'backdrop_path': '/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg',
   'genre_ids': [10751, 18],
   'id': 667257,
   'original_language': 'es',
   'original_title': 'Cosas imposibles',
   'overview': 'After the death of her abusive husband, Matilde finds her new best friend in Miguel, her young, insecure, and disoriented neighbor.',
   'popularity': 52.417,
   'poster_path': '/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg',
   'release_date': '2021-06-17',
   'title': 'Impossible Things',
   'video': False,
   'vote_average': 8.458,
   'vote_count': 380},
  {'adult': False,
   'backdrop_path': '/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg',
   'genre_ids': [16, 18, 10752],
   'id': 12477,
   'original_language': 'ja',
   'original_title': '火垂るの墓',
   'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
   'popularity': 0.058,
   'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
   'release_date': '1988-04-16',
   'title': 'Grave of the Fireflies',
   'video': False,
   'vote_average': 8.458,
   'vote_count': 5343},
  {'adult': False,
   'backdrop_path': '/7lyq8hK0MhPHpUXdnqbFvZYSfkk.jpg',
   'genre_ids': [18, 10749],
   'id': 11216,
   'original_language': 'it',
   'original_title': 'Nuovo Cinema Paradiso',
   'overview': "A filmmaker recalls his childhood, when he fell in love with the movies at his village's theater and formed a deep friendship with the theater's projectionist.",
   'popularity': 30.769,
   'poster_path': '/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg',
   'release_date': '1988-11-17',
   'title': 'Cinema Paradiso',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 4258}],
 'total_pages': 477,
 'total_results': 9534}

In [21]:
a=res.json()['results']

In [29]:
b=pd.DataFrame(a)

In [31]:
b.shape
b

,adult,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
0,False,/avedvodAZUcwqevBfm8p4G2NziQ.jpg,"[18, 80]",278,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,182.493,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,The Shawshank Redemption,False,8.705,26549
1,False,/tmU7GeKVybMWFButWEGl2M4GeiP.jpg,"[18, 80]",238,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",318.866,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,The Godfather,False,8.691,20154
2,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,131.333,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,The Godfather Part II,False,8.575,12161
3,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,en,Schindler's List,The true story of how businessman Oskar Schind...,128.348,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,Schindler's List,False,8.565,15565
4,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,en,12 Angry Men,The defense and the prosecution have rested an...,99.355,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,1957-04-10,12 Angry Men,False,8.543,8413
5,False,/m4TUa2ciEWSlk37rOsjiSIvZDXE.jpg,"[16, 10751, 14]",129,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",148.324,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-04-18,Spirited Away,False,8.537,16172
6,False,/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg,"[35, 18, 10749]",19404,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",88.589,/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg,1995-10-20,Dilwale Dulhania Le Jayenge,False,8.536,4410
7,False,/dqK9Hag1054tghRQSqLSfrkvQnA.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,202.793,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.516,32300
8,False,/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg,"[35, 53, 18]",496243,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",114.818,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,Parasite,False,8.508,17831
9,False,/vxJ08SvwomfKbpboCWynC3uqUg4.jpg,"[14, 18, 80]",497,en,The Green Mile,A supernatural tale set on death row in a Sout...,121.062,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,The Green Mile,False,8.506,17053
10,False,/dIWwZW7dJJtqC6CgWzYkNVKIUm8.jpg,"[16, 10749, 18]",372058,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,142.000,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-08-26,Your Name.,False,8.488,11147
11,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",139.372,/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg,1994-09-10,Pulp Fiction,False,8.500,27443
12,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,194.104,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-01,The Lord of the Rings: The Return of the King,False,8.482,23698
13,False,/ghgfzbEV7kbpbi1O8eIILKVXEA8.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,141.203,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,1994-06-23,Forrest Gump,False,8.475,26946
14,False,/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg,[37],429,it,"Il buono, il brutto, il cattivo",While the Civil War rages on between the Union...,123.889,/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg,1966-12-22,"The Good, the Bad and the Ugly",False,8.465,8401
15,False,/d6UxFCGQxpszcf8mwgGjQ3ynqGl.jpg,"[18, 80]",769,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",112.482,/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg,1990-09-12,GoodFellas,False,8.464,12591
16,False,/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg,"[28, 18]",346,ja,七人の侍,A samurai answers a village's request for prot...,86.673,/8OKmBV5BUFzmozIC3pPWKHy17kx.jpg,1954-04-26,Seven Samurai,False,8.461,3571
17,False,/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg,"[10751, 18]",667257,es,Cosas imposibles,"After the death of her abusive husband, Matild...",52.417,/t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg,2021-06-17,Impossible Things,False,8.458,380
18,False,/gwj4R8Uy1GwejKqfofREKI9Jh7L.jpg,"[16, 18, 10752]",12477,ja,火垂るの墓,"In the final months of World War II, 14-year-o...",0.058,/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg,1988-04-16,Grave of the Fireflies,False,8.458,5343
19,False,/7lyq8hK0MhPHpUXdnqbFvZYSfkk.jpg,"[18, 10749]",11216,it,Nuovo Cinema Paradiso,"A filmmaker recalls his childhood, when he fel...",30.769,/gCI2AeMV4IHSewhJkzsur5MEp6R.jpg,1988-11-17,Cinema Paradiso,False,8.500,4258

In [41]:
pd.DataFrame(a)[['title','vote_average','original_language','overview','vote_count']]

#OR ; a=(res.json()['results'])[['title','vote_average','original_language','overview','vote_count']]

,title,vote_average,original_language,overview,vote_count
0,The Shawshank Redemption,8.705,en,Imprisoned in the 1940s for the double murder ...,26549
1,The Godfather,8.691,en,"Spanning the years 1945 to 1955, a chronicle o...",20154
2,The Godfather Part II,8.575,en,In the continuing saga of the Corleone crime f...,12161
3,Schindler's List,8.565,en,The true story of how businessman Oskar Schind...,15565
4,12 Angry Men,8.543,en,The defense and the prosecution have rested an...,8413
5,Spirited Away,8.537,ja,"A young girl, Chihiro, becomes trapped in a st...",16172
6,Dilwale Dulhania Le Jayenge,8.536,hi,"Raj is a rich, carefree, happy-go-lucky second...",4410
7,The Dark Knight,8.516,en,Batman raises the stakes in his war on crime. ...,32300
8,Parasite,8.508,ko,"All unemployed, Ki-taek's family takes peculia...",17831
9,The Green Mile,8.506,en,A supernatural tale set on death row in a Sout...,17053
10,Your Name.,8.488,ja,High schoolers Mitsuha and Taki are complete s...,11147
11,Pulp Fiction,8.500,en,"A burger-loving hit man, his philosophical par...",27443
12,The Lord of the Rings: The Return of the King,8.482,en,As armies mass for a final battle that will de...,23698
13,Forrest Gump,8.475,en,A man with a low IQ has accomplished great thi...,26946
14,"The Good, the Bad and the Ugly",8.465,it,While the Civil War rages on between the Union...,8401
15,GoodFellas,8.464,en,"The true story of Henry Hill, a half-Irish, ha...",12591
16,Seven Samurai,8.461,ja,A samurai answers a village's request for prot...,3571
17,Impossible Things,8.458,es,"After the death of her abusive husband, Matild...",380
18,Grave of the Fireflies,8.458,ja,"In the final months of World War II, 14-year-o...",5343
19,Cinema Paradiso,8.500,it,"A filmmaker recalls his childhood, when he fel...",4258

In [5]:
df1=[]
for i in range(1,40):
    res = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(res.json()['results'])[['title','vote_average','original_language','overview','vote_count']]
    df1.append(temp_df)

ab = pd.concat(df1,ignore_index=True)
ab
#False due to new versions ma dataframe ma append nathi thatu , list ma use kari sakay

,title,vote_average,original_language,overview,vote_count
0,The Shawshank Redemption,8.705,en,Imprisoned in the 1940s for the double murder ...,26555
1,The Godfather,8.691,en,"Spanning the years 1945 to 1955, a chronicle o...",20157
2,The Godfather Part II,8.600,en,In the continuing saga of the Corleone crime f...,12164
3,Schindler's List,8.565,en,The true story of how businessman Oskar Schind...,15566
4,12 Angry Men,8.543,en,The defense and the prosecution have rested an...,8414
...,...,...,...,...,...
775,Rurouni Kenshin: The Final,7.702,ja,"In 1879, Kenshin and his allies face their str...",452
776,The Broken Circle Breakdown,7.702,nl,The loss of their young daughter threatens to ...,1027
777,Nosferatu,7.702,de,"In this highly influential silent horror film,...",1931
778,A Matter of Life and Death,7.701,en,When a young RAF pilot miraculously survives b...,395
779,Inherit the Wind,7.705,en,Schoolteacher Bertram Cates is arrested for te...,396

In [8]:
type(ab)

pandas.core.frame.DataFrame

In [10]:
ab.to_csv('40movies.csv')

<h1>BELOW CODE IS FROM CHATGPT</h1>

In [78]:
# Initialize an empty list to store DataFrames
dfs = []

# Loop through the pages
for i in range(1, 429):
    res = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={i}')
    if res.status_code == 200:
        temp_df = pd.DataFrame(res.json().get('results', []))[['title','vote_average','original_language','overview','vote_count']]
        dfs.append(temp_df)
    else:
        print(f"Failed to fetch data for page {i}: Status code {res.status_code}")

# Concatenate all DataFrames in the list into a single DataFrame
if dfs:
    df = pd.concat(dfs, ignore_index=True)
    print(df)
else:
    print("No data was fetched.")

                                      title  vote_average original_language  \
0                  The Shawshank Redemption         8.705                en
1                             The Godfather         8.691                en
2                     The Godfather Part II         8.600                en
3                          Schindler's List         8.565                en
4                              12 Angry Men         8.543                en
...                                     ...           ...               ...
8555                               The Pact         5.700                en
8556      American Pie Presents: Beta House         5.654                en
8557                      The Tax Collector         5.653                en
8558  Legally Blonde 2: Red, White & Blonde         5.652                en
8559                             The Ringer         5.654                en

                                               overview  vote_count
0     Imprisoned in the 1940s for the double murder ...       26555
1     Spanning the years 1945 to 1955, a chronicle o...       20157
2     In the continuing saga of the Corleone crime f...       12164
3     The true story of how businessman Oskar Schind...       15566
4     The defense and the prosecution have rested an...        8414
...                                                 ...         ...
8555  After their mother passes away, sisters Nicole...         466
8556  Erik, Ryan, and Cooze start college and pledge...        1840
8557  David Cuevas is a family man who works as a ga...         455
8558  Now a rising young lawyer, Elle Woods is about...        1518
8559  Pressured by a greedy uncle and a pile of debt...         315

[8560 rows x 5 columns]

In [102]:
type(df)

pandas.core.frame.DataFrame

In [108]:
df.to_csv('moviess.csv')